name: Build and Push Docker Image

# 언제 이 작업을 실행할까요?
on:
  push:
    branches: [ "main" ]  # main 브랜치에 코드가 올라오면 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # 1. GitHub 서버가 내 코드를 가져옵니다.
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker Hub에 로그인합니다. (설정했던 Secrets 사용)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. 이미지를 빌드하고 Docker Hub로 보냅니다.
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./DL/DS6_MLOps/MLOps_serving/
        file: ./DL/DS6_MLOps/MLOps_serving/dockerfile
        push: true
        # '아이디/이미지명:태그' 형식으로 적으세요.
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-ml-app:latest
        

#